rundeck:
  image:
    tag: 3.3.9

  ldap:
    host: placeholder
    bind:
      dn: placeholder
      password: placeholder
    user:
      dn: placeholder
    group:
      dn: placeholder

  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1152Mi

  ingress:
    host: placeholder
    tls:
      secretName: placeholder

options:
  image:
    tag: 1.0.0

  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

  gitlab:
    host: placeholder
    token: placeholder

mariadb:
  database: placeholder

  security:
    username: placeholder
    password: placeholder

  storage:
    class: resize-sc
    accessMode: ReadWriteOnce
    size: 2Gi

  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
      