apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  labels:
    app.funpresp.k8s/part-of: {{ .Release.Name }}
spec:
  ports:
    - name: sql
      port: 3306
      targetPort: 3306
  selector:
    app.funpresp.k8s/name: mariadb
    app.funpresp.k8s/instance: rundeck