apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-options
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.funpresp.k8s/name: rundeck
    app.funpresp.k8s/instance: options
    app.funpresp.k8s/part-of: {{ .Release.Name }}